# Data Cleaning Notebook
Week 4 IDX Exchange


Jack Phelan

# Setup

In [ ]:
#imports
import pandas as pd
import re
from geopy.geocoders import Nominatim
from tqdm import tqdm
from geopy.extra.rate_limiter import RateLimiter
from geopy.geocoders import Nominatim

In [107]:
# read in data
enriched_listings = pd.read_csv("./../data/enriched/listings_with_rates.csv", low_memory=False)
enriched_sold = pd.read_csv("./../data/enriched/sold_with_rates.csv", low_memory=False)

# Datetime Conversions

In [108]:
def dt_converter(df): 
    # Convert date fields to datetime format
    date_fields = ['CloseDate', 'PurchaseContractDate', 'ListingContractDate', 'ContractStatusChangeDate']
    for field in date_fields:
        if field in df.columns:
            df[field] = pd.to_datetime(df[field], errors='coerce')
    return df

In [109]:
enriched_listings.head(5)

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,BuyerAgencyCompensationType,BuyerAgencyCompensation,year_month
0,929000.0,1076194146,dianne@drector.com,NaN,NaN,Dianne,Rector,NaN,NaN,16882 Canyon Lane,...,Huntington Beach Union High,92649,NaN,330.0,1847.0,NaN,16882 Canyon Lane,NaN,NaN,2024-05
1,999999.0,1076194026,realestateby_denisegarcia@gmail.com,NaN,NaN,Denise,Garcia,NaN,NaN,8720 S 4th Avenue,...,Inglewood Unified,90305,NaN,0.0,8508.0,NaN,8720 S 4th Avenue,NaN,NaN,2024-05
2,1400000.0,1076193814,alizabethjames@hotmail.com,NaN,NaN,Alizabeth,James,33.858559,-116.542169,505 E Molino Road,...,Palm Springs Unified,92262,NaN,NaN,10890.0,NaN,505 E Molino Road,NaN,NaN,2024-05
3,4998888.0,1076193812,ernieramos62@yahoo.com,NaN,NaN,Ernesto,Ramos,NaN,NaN,3653 Halldale Avenue,...,NaN,90018,NaN,NaN,6192.0,NaN,3653 Halldale Avenue,NaN,NaN,2024-05
4,549000.0,1076193525,parsanina@yahoo.com,NaN,NaN,Nina,Parsa,NaN,NaN,1736 N Mcdivitt Avenue,...,Los Angeles Unified,90221,NaN,0.0,4113.0,NaN,1736 N Mcdivitt Avenue,NaN,NaN,2024-05

In [110]:
enriched_listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 893594 entries, 0 to 893593
Data columns (total 85 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             890150 non-null  float64
 1   ListingKey                    893594 non-null  int64
 2   ListAgentEmail                891222 non-null  object
 3   CloseDate                     257985 non-null  object
 4   ClosePrice                    233372 non-null  float64
 5   ListAgentFirstName            888314 non-null  object
 6   ListAgentLastName             893511 non-null  object
 7   Latitude                      781122 non-null  float64
 8   Longitude                     781848 non-null  float64
 9   UnparsedAddress               891239 non-null  object
 10  PropertyType                  893594 non-null  object
 11  LivingArea                    782759 non-null  float64
 12  ListPrice                     891376 non-null  float64
 13  DaysOnMarket                  893594 non-null  int64
 14  ListOfficeName                893594 non-null  object
 15  BuyerOfficeName               247055 non-null  object
 16  CoListOfficeName              179130 non-null  object
 17  ListAgentFullName             893335 non-null  object
 18  CoListAgentFirstName          178437 non-null  object
 19  CoListAgentLastName           178951 non-null  object
 20  BuyerAgentMlsId               248630 non-null  object
 21  BuyerAgentFirstName           248473 non-null  object
 22  BuyerAgentLastName            249390 non-null  object
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       258896 non-null  object
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             893594 non-null  int64
 27  MLSAreaMajor                  792414 non-null  object
 28  TaxAnnualAmount               6357 non-null    float64
 29  CountyOrParish                893593 non-null  object
 30  PropertyType.1                893594 non-null  object
 31  MlsStatus                     893594 non-null  object
 32  ElementarySchool              83104 non-null   object
 33  ListAgentFirstName.1          888314 non-null  object
 34  AttachedGarageYN              589448 non-null  object
 35  ParkingTotal                  839102 non-null  float64
 36  BuilderName                   30545 non-null   object
 37  PropertySubType               785189 non-null  object
 38  LotSizeAcres                  808569 non-null  float64
 39  SubdivisionName               298187 non-null  object
 40  BuyerOfficeAOR                235140 non-null  object
 41  YearBuilt                     821420 non-null  float64
 42  DaysOnMarket.1                893594 non-null  int64
 43  StreetNumberNumeric           889570 non-null  float64
 44  LivingArea.1                  782759 non-null  float64
 45  ListingId                     893594 non-null  object
 46  BathroomsTotalInteger         820694 non-null  float64
 47  City                          892617 non-null  object
 48  TaxYear                       901 non-null     float64
 49  BuildingAreaTotal             143313 non-null  float64
 50  BedroomsTotal                 786298 non-null  float64
 51  ContractStatusChangeDate      886138 non-null  object
 52  Longitude.1                   781848 non-null  float64
 53  ElementarySchoolDistrict      0 non-null       float64
 54  CoBuyerAgentFirstName         19810 non-null   object
 55  PurchaseContractDate          377495 non-null  object
 56  ListingContractDate           893594 non-null  object
 57  BelowGradeFinishedArea        3621 non-null    float64
 58  BusinessType                  6236 non-null    object
 59  Latitude.1                    781122 non-null  float64
 60  ListPrice.1                   891376 non-null  float64
 61  StateOrProvince               893525 non-null  object
 62  CoveredSpaces                 0 non-null       float64
 63  MiddleOrJuniorSchool          83097 non-null   object
 64  FireplaceYN                   765975 non-null  object
 65  Stories                       661815 non-null  float64
 66  HighSchool                    109303 non-null  object
 67  Levels                        721823 non-null  object
 68  ListAgentLastName.1           893511 non-null  object
 69  CloseDate.1                   257985 non-null  object
 70  LotSizeDimensions             51050 non-null   object
 71  LotSizeArea                   812504 non-null  float64
 72  MainLevelBedrooms             412951 non-null  float64
 73  NewConstructionYN             774028 non-null  object
 74  GarageSpaces                  724634 non-null  float64
 75  HighSchoolDistrict            538808 non-null  object
 76  PostalCode                    893376 non-null  object
 77  BuyerOfficeName.1             247055 non-null  object
 78  AssociationFee                604893 non-null  float64
 79  LotSizeSquareFeet             811392 non-null  float64
 80  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 81  UnparsedAddress.1             891239 non-null  object
 82  BuyerAgencyCompensationType   123538 non-null  object
 83  BuyerAgencyCompensation       123519 non-null  float64
 84  year_month                    893594 non-null  object
dtypes: float64(32), int64(4), object(49)
memory usage: 579.5+ MB

## Task List
- Convert date fields to datetime format (CloseDate, PurchaseContractDate, ListingContractDate, ContractStatusChangeDate) OK
- Remove unnecessary or redundant columns
- Handle missing values appropriately
- Ensure numeric fields are properly typed
- Remove or flag invalid numeric values: ClosePrice <= 0, LivingArea <= 0, DaysOnMarket < 0,
negative Bedrooms or Bathrooms

In [111]:
int_list = dt_converter(enriched_listings)

In [112]:
dt_cols = ['CloseDate', 'PurchaseContractDate', 'ListingContractDate', 'ContractStatusChangeDate']
int_list[dt_cols].head(5)

  CloseDate PurchaseContractDate ListingContractDate ContractStatusChangeDate
0       NaT                  NaT          2024-05-10               2024-05-10
1       NaT                  NaT          2024-05-30               2024-05-30
2       NaT                  NaT          2024-05-21               2024-05-21
3       NaT                  NaT          2024-05-29               2024-05-29
4       NaT                  NaT          2024-05-27               2024-05-27

# Removing Unnecessary Columns

In [113]:
cols = [
        "AboveGradeFinishedArea",
        'BelowGradeFinishedArea',
        "TaxAnnualAmount",
        "BuilderName",
        "ElementarySchoolDistrict",
        "BusinessType",
        "CoveredSpaces",
        "MiddleOrJuniorSchool",
        "MiddleOrJuniorSchoolDistrict",
        "Latitude.1",
        "Longitude.1",
        "UnparsedAddress.1"
    ]

In [114]:
int_list = int_list.drop(columns=cols,axis=1)

In [115]:
int_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 893594 entries, 0 to 893593
Data columns (total 73 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   OriginalListPrice            890150 non-null  float64
 1   ListingKey                   893594 non-null  int64
 2   ListAgentEmail               891222 non-null  object
 3   CloseDate                    257985 non-null  datetime64[ns]
 4   ClosePrice                   233372 non-null  float64
 5   ListAgentFirstName           888314 non-null  object
 6   ListAgentLastName            893511 non-null  object
 7   Latitude                     781122 non-null  float64
 8   Longitude                    781848 non-null  float64
 9   UnparsedAddress              891239 non-null  object
 10  PropertyType                 893594 non-null  object
 11  LivingArea                   782759 non-null  float64
 12  ListPrice                    891376 non-null  float64
 13  DaysOnMarket                 893594 non-null  int64
 14  ListOfficeName               893594 non-null  object
 15  BuyerOfficeName              247055 non-null  object
 16  CoListOfficeName             179130 non-null  object
 17  ListAgentFullName            893335 non-null  object
 18  CoListAgentFirstName         178437 non-null  object
 19  CoListAgentLastName          178951 non-null  object
 20  BuyerAgentMlsId              248630 non-null  object
 21  BuyerAgentFirstName          248473 non-null  object
 22  BuyerAgentLastName           249390 non-null  object
 23  FireplacesTotal              0 non-null       float64
 24  AssociationFeeFrequency      258896 non-null  object
 25  ListingKeyNumeric            893594 non-null  int64
 26  MLSAreaMajor                 792414 non-null  object
 27  CountyOrParish               893593 non-null  object
 28  PropertyType.1               893594 non-null  object
 29  MlsStatus                    893594 non-null  object
 30  ElementarySchool             83104 non-null   object
 31  ListAgentFirstName.1         888314 non-null  object
 32  AttachedGarageYN             589448 non-null  object
 33  ParkingTotal                 839102 non-null  float64
 34  PropertySubType              785189 non-null  object
 35  LotSizeAcres                 808569 non-null  float64
 36  SubdivisionName              298187 non-null  object
 37  BuyerOfficeAOR               235140 non-null  object
 38  YearBuilt                    821420 non-null  float64
 39  DaysOnMarket.1               893594 non-null  int64
 40  StreetNumberNumeric          889570 non-null  float64
 41  LivingArea.1                 782759 non-null  float64
 42  ListingId                    893594 non-null  object
 43  BathroomsTotalInteger        820694 non-null  float64
 44  City                         892617 non-null  object
 45  TaxYear                      901 non-null     float64
 46  BuildingAreaTotal            143313 non-null  float64
 47  BedroomsTotal                786298 non-null  float64
 48  ContractStatusChangeDate     886138 non-null  datetime64[ns]
 49  CoBuyerAgentFirstName        19810 non-null   object
 50  PurchaseContractDate         377495 non-null  datetime64[ns]
 51  ListingContractDate          893594 non-null  datetime64[ns]
 52  ListPrice.1                  891376 non-null  float64
 53  StateOrProvince              893525 non-null  object
 54  FireplaceYN                  765975 non-null  object
 55  Stories                      661815 non-null  float64
 56  HighSchool                   109303 non-null  object
 57  Levels                       721823 non-null  object
 58  ListAgentLastName.1          893511 non-null  object
 59  CloseDate.1                  257985 non-null  object
 60  LotSizeDimensions            51050 non-null   object
 61  LotSizeArea                  812504 non-null  float64
 62  MainLevelBedrooms            412951 non-null  float64
 63  NewConstructionYN            774028 non-null  object
 64  GarageSpaces                 724634 non-null  float64
 65  HighSchoolDistrict           538808 non-null  object
 66  PostalCode                   893376 non-null  object
 67  BuyerOfficeName.1            247055 non-null  object
 68  AssociationFee               604893 non-null  float64
 69  LotSizeSquareFeet            811392 non-null  float64
 70  BuyerAgencyCompensationType  123538 non-null  object
 71  BuyerAgencyCompensation      123519 non-null  float64
 72  year_month                   893594 non-null  object
dtypes: datetime64[ns](4), float64(24), int64(4), object(41)
memory usage: 497.7+ MB

In [116]:
agent_cols = [int for int in int_list.columns if re.search(r'Agent', int)]

agent_test = ['ListAgentFirstName', 'ListAgentLastName']
agent_test_1 = ['ListAgentFirstName.1', 'ListAgentLastName.1']
agent_test_full = agent_test + agent_test_1

first = ['ListAgentFirstName', 'ListAgentFirstName.1']
last = ['ListAgentLastName', 'ListAgentLastName.1']

In [117]:
int_list[agent_test_full].head(5)

,ListAgentFirstName,ListAgentLastName,ListAgentFirstName.1,ListAgentLastName.1
0,Dianne,Rector,Dianne,Rector
1,Denise,Garcia,Denise,Garcia
2,Alizabeth,James,Alizabeth,James
3,Ernesto,Ramos,Ernesto,Ramos
4,Nina,Parsa,Nina,Parsa

In [118]:
agent_drops = [
    "ListAgentEmail",
    "ListAgentFirstName",
    "ListAgentLastName",
    "ListAgentFirstName.1",
    "ListAgentLastName.1",
]

In [119]:
int_list = int_list.drop(columns=agent_drops)

In [120]:
int_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 893594 entries, 0 to 893593
Data columns (total 68 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   OriginalListPrice            890150 non-null  float64
 1   ListingKey                   893594 non-null  int64
 2   CloseDate                    257985 non-null  datetime64[ns]
 3   ClosePrice                   233372 non-null  float64
 4   Latitude                     781122 non-null  float64
 5   Longitude                    781848 non-null  float64
 6   UnparsedAddress              891239 non-null  object
 7   PropertyType                 893594 non-null  object
 8   LivingArea                   782759 non-null  float64
 9   ListPrice                    891376 non-null  float64
 10  DaysOnMarket                 893594 non-null  int64
 11  ListOfficeName               893594 non-null  object
 12  BuyerOfficeName              247055 non-null  object
 13  CoListOfficeName             179130 non-null  object
 14  ListAgentFullName            893335 non-null  object
 15  CoListAgentFirstName         178437 non-null  object
 16  CoListAgentLastName          178951 non-null  object
 17  BuyerAgentMlsId              248630 non-null  object
 18  BuyerAgentFirstName          248473 non-null  object
 19  BuyerAgentLastName           249390 non-null  object
 20  FireplacesTotal              0 non-null       float64
 21  AssociationFeeFrequency      258896 non-null  object
 22  ListingKeyNumeric            893594 non-null  int64
 23  MLSAreaMajor                 792414 non-null  object
 24  CountyOrParish               893593 non-null  object
 25  PropertyType.1               893594 non-null  object
 26  MlsStatus                    893594 non-null  object
 27  ElementarySchool             83104 non-null   object
 28  AttachedGarageYN             589448 non-null  object
 29  ParkingTotal                 839102 non-null  float64
 30  PropertySubType              785189 non-null  object
 31  LotSizeAcres                 808569 non-null  float64
 32  SubdivisionName              298187 non-null  object
 33  BuyerOfficeAOR               235140 non-null  object
 34  YearBuilt                    821420 non-null  float64
 35  DaysOnMarket.1               893594 non-null  int64
 36  StreetNumberNumeric          889570 non-null  float64
 37  LivingArea.1                 782759 non-null  float64
 38  ListingId                    893594 non-null  object
 39  BathroomsTotalInteger        820694 non-null  float64
 40  City                         892617 non-null  object
 41  TaxYear                      901 non-null     float64
 42  BuildingAreaTotal            143313 non-null  float64
 43  BedroomsTotal                786298 non-null  float64
 44  ContractStatusChangeDate     886138 non-null  datetime64[ns]
 45  CoBuyerAgentFirstName        19810 non-null   object
 46  PurchaseContractDate         377495 non-null  datetime64[ns]
 47  ListingContractDate          893594 non-null  datetime64[ns]
 48  ListPrice.1                  891376 non-null  float64
 49  StateOrProvince              893525 non-null  object
 50  FireplaceYN                  765975 non-null  object
 51  Stories                      661815 non-null  float64
 52  HighSchool                   109303 non-null  object
 53  Levels                       721823 non-null  object
 54  CloseDate.1                  257985 non-null  object
 55  LotSizeDimensions            51050 non-null   object
 56  LotSizeArea                  812504 non-null  float64
 57  MainLevelBedrooms            412951 non-null  float64
 58  NewConstructionYN            774028 non-null  object
 59  GarageSpaces                 724634 non-null  float64
 60  HighSchoolDistrict           538808 non-null  object
 61  PostalCode                   893376 non-null  object
 62  BuyerOfficeName.1            247055 non-null  object
 63  AssociationFee               604893 non-null  float64
 64  LotSizeSquareFeet            811392 non-null  float64
 65  BuyerAgencyCompensationType  123538 non-null  object
 66  BuyerAgencyCompensation      123519 non-null  float64
 67  year_month                   893594 non-null  object
dtypes: datetime64[ns](4), float64(24), int64(4), object(36)
memory usage: 463.6+ MB

# Numeric Type Checking

In [121]:
int_list = int_list.copy()

In [122]:
parking_vals = int_list['ParkingTotal'].unique()

display(parking_vals) # are half parking spaces valid? idk

array([ 2.000000e+00,  0.000000e+00,  3.000000e+00,  1.000000e+00,
        4.000000e+00,           nan,  6.000000e+00,  8.000000e+00,
        9.000000e+00,  5.000000e+00,  1.000000e+01,  1.200000e+01,
        7.000000e+00,  1.800000e+01,  8.400000e+01,  2.000000e+01,
        2.200000e+01,  6.500000e+00,  2.400000e+01,  1.400000e+01,
        1.700000e+01,  3.000000e+01,  2.300000e+01,  1.100000e+01,
        2.500000e+00,  5.500000e+00,  1.300000e+01,  1.600000e+01,
        3.780000e+02,  5.240000e+02,  1.500000e+00,  1.500000e+01,
        1.000000e+03, -2.000000e+00,  2.500000e+01,  2.600000e+01,
        2.100000e+01,  1.340000e+02,  1.430000e+02,  3.300000e+01,
        4.000000e+01,  1.900000e+01,  5.000000e+01,  2.900000e+01,
        2.700000e+01,  4.500000e+00,  4.800000e+01,  7.800000e+02,
        1.000000e+02,  4.000000e+02,  3.600000e+01,  8.200000e+01,
        3.100000e+01,  6.000000e+01,  3.700000e+01,  3.200000e+01,
        4.900000e+01,  4.500000e+02, -7.000000e+00,  7.300000e+01,
        7.500000e+00,  8.500000e+00,  5.000000e-01,  1.640000e+02,
       -1.100000e+01,  2.800000e+01,  3.000000e+02,  6.000000e+02,
        3.600000e+02,  8.000000e+01,  1.000900e+04,  5.600000e+02,
        4.400000e+02,  6.600000e+01,  2.500000e-01, -4.000000e+00,
        5.300000e+01, -2.700000e+01, -1.000000e+01,  1.560000e+02,
       -2.000000e+01, -2.200000e+01,  2.500000e+02,  7.600000e+01,
        1.500000e+02,  6.600000e+02,  6.210000e+02,  6.500000e+01,
        4.500000e+01,  3.400000e+01,  5.900000e+01, -3.000000e+00,
        4.400000e+01,  6.400000e+01,  3.500000e+00,  4.200000e+01,
        2.000000e+02,  5.500000e+01,  4.100000e+01,  1.020000e+02,
        6.300000e+02, -8.000000e+00,  7.400000e+01,  5.200000e+01,
        3.900000e+01,  3.500000e+01, -5.000000e+00, -1.600000e+01,
        1.760000e+02,  4.620000e+02,  1.450000e+01,  9.000000e+01,
        5.800000e+01,  1.200000e+02,  8.700000e+01,  6.030000e+02,
        1.310000e+02,  1.020000e+03,  1.150000e+02, -6.500000e+01,
        1.050000e+01,  6.300000e+01,  9.630000e+02,  1.520000e+02,
        3.500000e+02,  1.630000e+02,  4.530000e+02, -3.700000e+01,
        1.350000e+02,  7.700000e+01,  1.396000e+03,  5.760000e+02,
        6.170000e+02,  5.000000e+02,  5.100000e+01, -1.500000e+01,
        3.800000e+01,  1.100000e+02,  2.240000e+02,  8.500000e+01,
        3.000000e+03,  8.500000e+02,  3.530000e+02,  7.200000e+01,
        9.500000e+01,  7.000000e+01,  4.600000e+01,  1.690000e+02,
        9.990000e+02,  4.340000e+02,  4.700000e+01,  2.250000e+02,
        1.700000e+02,  7.000000e+02,  1.050000e+02,  7.900000e+01,
       -2.100000e+01,  1.006000e+03,  1.250000e+02, -6.000000e+00,
        7.500000e+01,  4.840000e+02,  7.440000e+02,  5.200000e+02,
        4.030000e+02,  4.443000e+01,  1.388000e+03,  5.600000e+01,
        2.250000e+00,  4.490000e+02,  1.342000e+03,  5.070000e+02,
       -1.900000e+01,  3.630000e+02,  1.620000e+02, -1.150000e+02,
        4.800000e+02,  6.200000e+01,  4.300000e+01,  8.370000e+02,
        5.700000e+01,  1.135000e+03,  2.390000e+02,  4.250000e+02,
        1.400000e+02,  1.580000e+02,  2.650000e+01,  9.100000e+01,
        8.380000e+02,  1.670000e+02,  2.178000e+03,  1.250000e+01,
        1.040000e+02,  1.003000e+03,  1.243000e+03,  1.215000e+03,
        1.150000e+01,  1.550000e+02,  9.700000e+01,  1.110000e+02,
        5.400000e+01,  4.040000e+02,  1.419000e+03,  1.949000e+03,
        9.500000e+00,  4.010000e+02,  1.060000e+02,  4.220000e+02,
        2.250000e+01,  5.170000e+02,  7.100000e+01,  1.180000e+02,
        1.490000e+03,  9.300000e+01,  3.590000e+02,  6.800000e+01,
       -9.000000e+00,  2.530000e+02,  5.500000e+02,  1.030000e+02,
        4.510000e+02,  1.010000e+02,  2.380000e+02,  9.000000e+02,
        7.800000e+01,  6.700000e+01,  1.750000e+02,  9.900000e+01,
        2.426000e+03,  2.800000e+02,  2.370000e+02,  9.400000e+01,
        5.180000e+02,  8.600000e+01,  6.962000e+03,  1.920000e+02,
        8.900000e+01, -1.200000e+01,  2.060000e+02,  2.260000e+02,
        3.610000e+02,  6.500000e+02,  4.050000e+02,  3.100000e+02,
        4.970000e+02,  6.340000e+02,  2.560000e+02,  4.610000e+02,
        9.800000e+01,  4.320000e+02,  4.660000e+02,  1.190000e+02,
        2.593669e+06,  4.520000e+02,  1.380000e+02,  1.160000e+02,
        6.250000e+02,  4.890000e+02,  2.130000e+02,  6.154000e+03,
       -1.390000e+02,  2.540000e+02,  4.400000e-01,  1.720000e+02,
        5.250000e+02,  3.250000e+00,  1.270000e+02,  1.100000e+03,
        3.050000e+02,  1.480000e+02, -1.400000e+01,  4.210000e+02,
       -2.400000e+01,  6.800000e+02,  8.300000e+01,  4.480000e+02,
       -1.000000e+00,  1.052200e+04,  3.930000e+02,  2.450000e+02,
        6.200000e+02,  1.490000e+02,  1.980000e+02,  3.921000e+03,
        4.200000e+02,  3.800000e+02,  3.410000e+02,  4.270000e+02,
        4.590000e+02,  2.490000e+02,  1.600000e+02,  2.242800e+04,
        2.120000e+02,  5.560000e+02,  6.510000e+02,  4.740000e+02,
        4.780000e+02,  2.200000e+02,  4.120000e+02,  2.600000e+02,
        3.980000e+02, -1.300000e+01,  1.651000e+03,  6.670000e+02,
        8.800000e+03,  2.970000e+02,  1.350000e+01,  2.310000e+02,
       -3.000000e+01,  2.400000e+02, -3.600000e+01,  2.630000e+02,
        8.100000e+01,  1.420000e+02,  9.600000e+01,  2.150000e+02,
       -4.600000e+01,  6.780000e+02, -3.500000e+01,  1.710000e+02,
        1.075000e+01,  1.173700e+04,  4.791000e+03,  1.570000e+02,
        1.001000e+03,  5.740000e+02,  4.190000e+02,  4.330000e+02,
        4.600000e+02,  2.940000e+02,  1.780000e+02,  4.960000e+02,
        4.680000e+02,  2.550000e+02, -2.300000e+01,  1.572000e+04,
       -2.800000e+01,  2.642800e+04,  2.860000e+02, -1.700000e+01,
        3.055000e+03,  3.275000e+03,  2.420000e+02,  1.300000e+02,
        8.930000e+02,  1.140000e+02, -1.430000e+02,  1.220000e+02,
        2.040000e+02, -5.100000e+01,  3.870000e+02,  1.930000e+02,
        6.620000e+02,  6.900000e+01,  8.000000e+02,  1.090000e+02,
        1.360000e+02, -1.800000e+01,  2.090000e+02,  1.260000e+03,
       -1.180000e+02, -2.600000e+01,  1.111000e+03, -2.500000e+01,
        1.260000e+02,  1.900000e+02,  2.430000e+02,  4.410000e+02,
        1.800000e+02,  2.100000e+00,  2.220000e+02,  1.880000e+02,
        6.100000e+01,  4.830000e+02, -2.900000e+01,  2.180000e+02,
        4.140000e+02,  8.210000e+02,  2.520000e+02,  1.970000e+02,
        4.910000e+02,  5.030000e+02,  4.344000e+03,  5.020000e+02,
        1.470000e+02,  2.507000e+03,  1.330000e+02,  1.810000e+02,
        1.410000e+02,  4.170000e+02,  2.060840e+05,  4.240000e+02,
       -7.100000e+01,  4.150000e+02,  5.060000e+02,  7.140000e+02,
       -6.100000e+01,  2.680000e+02])

In [123]:
to_int_cols = [
    "YearBuilt",
    "StreetNumberNumeric",
    "BathroomsTotalInteger",
    "TaxYear",
    "Stories",
]

int_list[to_int_cols] = int_list[to_int_cols].astype("Int64")

In [124]:
int_list.head()

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,ListPrice,...,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,BuyerAgencyCompensationType,BuyerAgencyCompensation,year_month
0,929000.0,1076194146,NaT,NaN,NaN,NaN,16882 Canyon Lane,Residential,1389.0,929000.0,...,False,2.0,Huntington Beach Union High,92649,NaN,330.0,1847.0,NaN,NaN,2024-05
1,999999.0,1076194026,NaT,NaN,NaN,NaN,8720 S 4th Avenue,Residential,2526.0,999999.0,...,False,2.0,Inglewood Unified,90305,NaN,0.0,8508.0,NaN,NaN,2024-05
2,1400000.0,1076193814,NaT,NaN,33.858559,-116.542169,505 E Molino Road,Residential,2256.0,1400000.0,...,False,2.0,Palm Springs Unified,92262,NaN,NaN,10890.0,NaN,NaN,2024-05
3,4998888.0,1076193812,NaT,NaN,NaN,NaN,3653 Halldale Avenue,ResidentialIncome,NaN,4998888.0,...,True,0.0,NaN,90018,NaN,NaN,6192.0,NaN,NaN,2024-05
4,549000.0,1076193525,NaT,NaN,NaN,NaN,1736 N Mcdivitt Avenue,Residential,986.0,549000.0,...,False,2.0,Los Angeles Unified,90221,NaN,0.0,4113.0,NaN,NaN,2024-05

# Missing Value Handling

Imputation strategies:
- Impute geographic location with knn of similar geography things
- then perhaps groupwise imputation for numeric values based on property type and location and maybe listing price range

## Geographic imputation

In [131]:
geo_cols = [
    "Latitude",
    "Longitude",
    "UnparsedAddress",
    "MLSAreaMajor",
    "CountyOrParish",
    "City",
    "StateOrProvince",
    "PostalCode",
]

In [132]:
int_list[geo_cols].head(5)

,Latitude,Longitude,UnparsedAddress,MLSAreaMajor,CountyOrParish,City,StateOrProvince,PostalCode
0,NaN,NaN,16882 Canyon Lane,17 - Northwest Huntington Beach,Orange,Huntington Beach,CA,92649
1,NaN,NaN,8720 S 4th Avenue,699 - Not Defined,Los Angeles,Inglewood,CA,90305
2,33.858559,-116.542169,505 E Molino Road,331 - North End Palm Springs,Riverside,Palm Springs,CA,92262
3,NaN,NaN,3653 Halldale Avenue,C42 - Downtown L.A.,Los Angeles,Los Angeles,CA,90018
4,NaN,NaN,1736 N Mcdivitt Avenue,"RN - Compton N of Rosecrans, E of Central",Los Angeles,Compton,CA,90221

In [ ]:
int_list["full_address"] = int_list["UnparsedAddress"].astype(str) + ", " + int_list["City"].astype(str) + ", " + int_list["StateOrProvince"].astype(str) + ", " + int_list["PostalCode"].astype(str)
int_list["full_address"].head(5)

0    16882 Canyon Lane, Huntington Beach, CA, 92649
1           8720 S 4th Avenue, Inglewood, CA, 90305
2        505 E Molino Road, Palm Springs, CA, 92262
3      3653 Halldale Avenue, Los Angeles, CA, 90018
4        1736 N Mcdivitt Avenue, Compton, CA, 90221
Name: full_address, dtype: object

In [ ]:
tqdm.pandas()

def bulk_geocode(df, address_column, output_path):
    # 1. Load your dataset
    # df is now passed directly, no need to read from CSV
    
    # 2. Initialize geocoder (Replace user_agent with your application name)
    # Nominatim is free but requires a distinct user_agent string
    locator = Nominatim(user_agent="my_bulk_geocoder_application_v1")
    
    # 3. Create a rate limiter 
    # Nominatim usage policy strictly requires a minimum 1-second delay between requests
    geocode = RateLimiter(locator.geocode, min_delay_seconds=1)
    
    print("Starting bulk geolocation...")
    
    # 4. Apply geocoding with a visible progress bar
    df['location'] = df[address_column].progress_apply(geocode)
    
    # 5. Extract Latitude and Longitude from the location object
    df['latitude'] = df['location'].apply(lambda loc: loc.latitude if loc else None)
    df['longitude'] = df['location'].apply(lambda loc: loc.longitude if loc else None)
    
    # Drop the temporary raw location object column before saving
    df = df.drop(columns=['location'])
    
    # 6. Save the results
    df.to_csv(output_path, index=False)
    print(f"Success! Saved results to {output_path}")

    return df

# Example Usage:
# bulk_geocode("addresses.csv", "Full_Address", "geocoded_output.csv")

In [143]:
# getting all lat and long coords from the unparsed addresses
# THIS WILL TAKE 10 DAYS :)
address_df = int_list[["full_address"]].copy()

address_df.to_csv("./../data/enriched/geo_enc/address_df.csv", index=False)

output_path = "./../data/enriched/geo_enc/geocoded_listings.csv"

#encoded = bulk_geocode(address_df, "full_address", output_path)

## Imputing elsewhere
- price range
- county/zip or city
- year built maybe
- floors, area quartiles
( lots of options figure it out at some point)