# Data Cleaning Notebook
Week 4 IDX Exchange


Jack Phelan

# Setup

In [43]:
#imports
import pandas as pd
import re

In [44]:
# read in data
enriched_listings = pd.read_csv("./../data/enriched/listings_with_rates.csv", low_memory=False)
enriched_sold = pd.read_csv("./../data/enriched/sold_with_rates.csv", low_memory=False)

# Datetime Conversions

In [45]:
def dt_converter(df): 
    # Convert date fields to datetime format
    date_fields = ['CloseDate', 'PurchaseContractDate', 'ListingContractDate', 'ContractStatusChangeDate']
    for field in date_fields:
        if field in df.columns:
            df[field] = pd.to_datetime(df[field], errors='coerce')
    return df

In [46]:
enriched_listings.head(5)

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,BuyerAgencyCompensationType,BuyerAgencyCompensation,year_month
0,929000.0,1076194146,dianne@drector.com,NaN,NaN,Dianne,Rector,NaN,NaN,16882 Canyon Lane,...,Huntington Beach Union High,92649,NaN,330.0,1847.0,NaN,16882 Canyon Lane,NaN,NaN,2024-05
1,999999.0,1076194026,realestateby_denisegarcia@gmail.com,NaN,NaN,Denise,Garcia,NaN,NaN,8720 S 4th Avenue,...,Inglewood Unified,90305,NaN,0.0,8508.0,NaN,8720 S 4th Avenue,NaN,NaN,2024-05
2,1400000.0,1076193814,alizabethjames@hotmail.com,NaN,NaN,Alizabeth,James,33.858559,-116.542169,505 E Molino Road,...,Palm Springs Unified,92262,NaN,NaN,10890.0,NaN,505 E Molino Road,NaN,NaN,2024-05
3,4998888.0,1076193812,ernieramos62@yahoo.com,NaN,NaN,Ernesto,Ramos,NaN,NaN,3653 Halldale Avenue,...,NaN,90018,NaN,NaN,6192.0,NaN,3653 Halldale Avenue,NaN,NaN,2024-05
4,549000.0,1076193525,parsanina@yahoo.com,NaN,NaN,Nina,Parsa,NaN,NaN,1736 N Mcdivitt Avenue,...,Los Angeles Unified,90221,NaN,0.0,4113.0,NaN,1736 N Mcdivitt Avenue,NaN,NaN,2024-05

In [58]:
enriched_listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 893594 entries, 0 to 893593
Data columns (total 85 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             890150 non-null  float64
 1   ListingKey                    893594 non-null  int64
 2   ListAgentEmail                891222 non-null  object
 3   CloseDate                     257985 non-null  datetime64[ns]
 4   ClosePrice                    233372 non-null  float64
 5   ListAgentFirstName            888314 non-null  object
 6   ListAgentLastName             893511 non-null  object
 7   Latitude                      781122 non-null  float64
 8   Longitude                     781848 non-null  float64
 9   UnparsedAddress               891239 non-null  object
 10  PropertyType                  893594 non-null  object
 11  LivingArea                    782759 non-null  float64
 12  ListPrice                     891376 non-null  float64
 13  DaysOnMarket                  893594 non-null  int64
 14  ListOfficeName                893594 non-null  object
 15  BuyerOfficeName               247055 non-null  object
 16  CoListOfficeName              179130 non-null  object
 17  ListAgentFullName             893335 non-null  object
 18  CoListAgentFirstName          178437 non-null  object
 19  CoListAgentLastName           178951 non-null  object
 20  BuyerAgentMlsId               248630 non-null  object
 21  BuyerAgentFirstName           248473 non-null  object
 22  BuyerAgentLastName            249390 non-null  object
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       258896 non-null  object
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             893594 non-null  int64
 27  MLSAreaMajor                  792414 non-null  object
 28  TaxAnnualAmount               6357 non-null    float64
 29  CountyOrParish                893593 non-null  object
 30  PropertyType.1                893594 non-null  object
 31  MlsStatus                     893594 non-null  object
 32  ElementarySchool              83104 non-null   object
 33  ListAgentFirstName.1          888314 non-null  object
 34  AttachedGarageYN              589448 non-null  object
 35  ParkingTotal                  839102 non-null  float64
 36  BuilderName                   30545 non-null   object
 37  PropertySubType               785189 non-null  object
 38  LotSizeAcres                  808569 non-null  float64
 39  SubdivisionName               298187 non-null  object
 40  BuyerOfficeAOR                235140 non-null  object
 41  YearBuilt                     821420 non-null  float64
 42  DaysOnMarket.1                893594 non-null  int64
 43  StreetNumberNumeric           889570 non-null  float64
 44  LivingArea.1                  782759 non-null  float64
 45  ListingId                     893594 non-null  object
 46  BathroomsTotalInteger         820694 non-null  float64
 47  City                          892617 non-null  object
 48  TaxYear                       901 non-null     float64
 49  BuildingAreaTotal             143313 non-null  float64
 50  BedroomsTotal                 786298 non-null  float64
 51  ContractStatusChangeDate      886138 non-null  datetime64[ns]
 52  Longitude.1                   781848 non-null  float64
 53  ElementarySchoolDistrict      0 non-null       float64
 54  CoBuyerAgentFirstName         19810 non-null   object
 55  PurchaseContractDate          377495 non-null  datetime64[ns]
 56  ListingContractDate           893594 non-null  datetime64[ns]
 57  BelowGradeFinishedArea        3621 non-null    float64
 58  BusinessType                  6236 non-null    object
 59  Latitude.1                    781122 non-null  float64
 60  ListPrice.1                   891376 non-null  float64
 61  StateOrProvince               893525 non-null  object
 62  CoveredSpaces                 0 non-null       float64
 63  MiddleOrJuniorSchool          83097 non-null   object
 64  FireplaceYN                   765975 non-null  object
 65  Stories                       661815 non-null  float64
 66  HighSchool                    109303 non-null  object
 67  Levels                        721823 non-null  object
 68  ListAgentLastName.1           893511 non-null  object
 69  CloseDate.1                   257985 non-null  object
 70  LotSizeDimensions             51050 non-null   object
 71  LotSizeArea                   812504 non-null  float64
 72  MainLevelBedrooms             412951 non-null  float64
 73  NewConstructionYN             774028 non-null  object
 74  GarageSpaces                  724634 non-null  float64
 75  HighSchoolDistrict            538808 non-null  object
 76  PostalCode                    893376 non-null  object
 77  BuyerOfficeName.1             247055 non-null  object
 78  AssociationFee                604893 non-null  float64
 79  LotSizeSquareFeet             811392 non-null  float64
 80  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 81  UnparsedAddress.1             891239 non-null  object
 82  BuyerAgencyCompensationType   123538 non-null  object
 83  BuyerAgencyCompensation       123519 non-null  float64
 84  year_month                    893594 non-null  object
dtypes: datetime64[ns](4), float64(32), int64(4), object(45)
memory usage: 579.5+ MB

## Task List
- Convert date fields to datetime format (CloseDate, PurchaseContractDate, ListingContractDate, ContractStatusChangeDate) OK
- Remove unnecessary or redundant columns
- Handle missing values appropriately
- Ensure numeric fields are properly typed
- Remove or flag invalid numeric values: ClosePrice <= 0, LivingArea <= 0, DaysOnMarket < 0,
negative Bedrooms or Bathrooms

In [47]:
int_list = dt_converter(enriched_listings)

In [48]:
dt_cols = ['CloseDate', 'PurchaseContractDate', 'ListingContractDate', 'ContractStatusChangeDate']
int_list[dt_cols].head(5)

  CloseDate PurchaseContractDate ListingContractDate ContractStatusChangeDate
0       NaT                  NaT          2024-05-10               2024-05-10
1       NaT                  NaT          2024-05-30               2024-05-30
2       NaT                  NaT          2024-05-21               2024-05-21
3       NaT                  NaT          2024-05-29               2024-05-29
4       NaT                  NaT          2024-05-27               2024-05-27

# Removing Unnecessary Columns

In [ ]:
cols = [
        "AboveGradeFinishedArea",
        'BelowGradeFinishedArea',
        "TaxAnnualAmount",
        "BuilderName",
        "ElementarySchoolDistrict",
        "BusinessType",
        "CoveredSpaces",
        "MiddleOrJuniorSchool",
        "MiddleOrJuniorSchoolDistrict",
    ]

In [50]:
int_list = int_list.drop(columns=cols,axis=1)

In [51]:
int_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 893594 entries, 0 to 893593
Data columns (total 77 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   OriginalListPrice            890150 non-null  float64
 1   ListingKey                   893594 non-null  int64
 2   ListAgentEmail               891222 non-null  object
 3   CloseDate                    257985 non-null  datetime64[ns]
 4   ClosePrice                   233372 non-null  float64
 5   ListAgentFirstName           888314 non-null  object
 6   ListAgentLastName            893511 non-null  object
 7   Latitude                     781122 non-null  float64
 8   Longitude                    781848 non-null  float64
 9   UnparsedAddress              891239 non-null  object
 10  PropertyType                 893594 non-null  object
 11  LivingArea                   782759 non-null  float64
 12  ListPrice                    891376 non-null  float64
 13  DaysOnMarket                 893594 non-null  int64
 14  ListOfficeName               893594 non-null  object
 15  BuyerOfficeName              247055 non-null  object
 16  CoListOfficeName             179130 non-null  object
 17  ListAgentFullName            893335 non-null  object
 18  CoListAgentFirstName         178437 non-null  object
 19  CoListAgentLastName          178951 non-null  object
 20  BuyerAgentMlsId              248630 non-null  object
 21  BuyerAgentFirstName          248473 non-null  object
 22  BuyerAgentLastName           249390 non-null  object
 23  FireplacesTotal              0 non-null       float64
 24  AssociationFeeFrequency      258896 non-null  object
 25  ListingKeyNumeric            893594 non-null  int64
 26  MLSAreaMajor                 792414 non-null  object
 27  CountyOrParish               893593 non-null  object
 28  PropertyType.1               893594 non-null  object
 29  MlsStatus                    893594 non-null  object
 30  ElementarySchool             83104 non-null   object
 31  ListAgentFirstName.1         888314 non-null  object
 32  AttachedGarageYN             589448 non-null  object
 33  ParkingTotal                 839102 non-null  float64
 34  PropertySubType              785189 non-null  object
 35  LotSizeAcres                 808569 non-null  float64
 36  SubdivisionName              298187 non-null  object
 37  BuyerOfficeAOR               235140 non-null  object
 38  YearBuilt                    821420 non-null  float64
 39  DaysOnMarket.1               893594 non-null  int64
 40  StreetNumberNumeric          889570 non-null  float64
 41  LivingArea.1                 782759 non-null  float64
 42  ListingId                    893594 non-null  object
 43  BathroomsTotalInteger        820694 non-null  float64
 44  City                         892617 non-null  object
 45  TaxYear                      901 non-null     float64
 46  BuildingAreaTotal            143313 non-null  float64
 47  BedroomsTotal                786298 non-null  float64
 48  ContractStatusChangeDate     886138 non-null  datetime64[ns]
 49  Longitude.1                  781848 non-null  float64
 50  CoBuyerAgentFirstName        19810 non-null   object
 51  PurchaseContractDate         377495 non-null  datetime64[ns]
 52  ListingContractDate          893594 non-null  datetime64[ns]
 53  BelowGradeFinishedArea       3621 non-null    float64
 54  Latitude.1                   781122 non-null  float64
 55  ListPrice.1                  891376 non-null  float64
 56  StateOrProvince              893525 non-null  object
 57  FireplaceYN                  765975 non-null  object
 58  Stories                      661815 non-null  float64
 59  HighSchool                   109303 non-null  object
 60  Levels                       721823 non-null  object
 61  ListAgentLastName.1          893511 non-null  object
 62  CloseDate.1                  257985 non-null  object
 63  LotSizeDimensions            51050 non-null   object
 64  LotSizeArea                  812504 non-null  float64
 65  MainLevelBedrooms            412951 non-null  float64
 66  NewConstructionYN            774028 non-null  object
 67  GarageSpaces                 724634 non-null  float64
 68  HighSchoolDistrict           538808 non-null  object
 69  PostalCode                   893376 non-null  object
 70  BuyerOfficeName.1            247055 non-null  object
 71  AssociationFee               604893 non-null  float64
 72  LotSizeSquareFeet            811392 non-null  float64
 73  UnparsedAddress.1            891239 non-null  object
 74  BuyerAgencyCompensationType  123538 non-null  object
 75  BuyerAgencyCompensation      123519 non-null  float64
 76  year_month                   893594 non-null  object
dtypes: datetime64[ns](4), float64(27), int64(4), object(42)
memory usage: 525.0+ MB

In [52]:
agent_cols = [int for int in int_list.columns if re.search(r'Agent', int)]

agent_test = ['ListAgentFirstName', 'ListAgentLastName']
agent_test_1 = ['ListAgentFirstName.1', 'ListAgentLastName.1']
agent_test_full = agent_test + agent_test_1

first = ['ListAgentFirstName', 'ListAgentFirstName.1']
last = ['ListAgentLastName', 'ListAgentLastName.1']

In [53]:
int_list[agent_test_full].head(5)

,ListAgentFirstName,ListAgentLastName,ListAgentFirstName.1,ListAgentLastName.1
0,Dianne,Rector,Dianne,Rector
1,Denise,Garcia,Denise,Garcia
2,Alizabeth,James,Alizabeth,James
3,Ernesto,Ramos,Ernesto,Ramos
4,Nina,Parsa,Nina,Parsa

In [54]:
agent_drops = [
    "ListAgentEmail",
    "ListAgentFirstName",
    "ListAgentLastName",
    "ListAgentFirstName.1",
    "ListAgentLastName.1",
]

In [56]:
int_list = int_list.drop(columns=agent_drops)

In [57]:
int_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 893594 entries, 0 to 893593
Data columns (total 72 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   OriginalListPrice            890150 non-null  float64
 1   ListingKey                   893594 non-null  int64
 2   CloseDate                    257985 non-null  datetime64[ns]
 3   ClosePrice                   233372 non-null  float64
 4   Latitude                     781122 non-null  float64
 5   Longitude                    781848 non-null  float64
 6   UnparsedAddress              891239 non-null  object
 7   PropertyType                 893594 non-null  object
 8   LivingArea                   782759 non-null  float64
 9   ListPrice                    891376 non-null  float64
 10  DaysOnMarket                 893594 non-null  int64
 11  ListOfficeName               893594 non-null  object
 12  BuyerOfficeName              247055 non-null  object
 13  CoListOfficeName             179130 non-null  object
 14  ListAgentFullName            893335 non-null  object
 15  CoListAgentFirstName         178437 non-null  object
 16  CoListAgentLastName          178951 non-null  object
 17  BuyerAgentMlsId              248630 non-null  object
 18  BuyerAgentFirstName          248473 non-null  object
 19  BuyerAgentLastName           249390 non-null  object
 20  FireplacesTotal              0 non-null       float64
 21  AssociationFeeFrequency      258896 non-null  object
 22  ListingKeyNumeric            893594 non-null  int64
 23  MLSAreaMajor                 792414 non-null  object
 24  CountyOrParish               893593 non-null  object
 25  PropertyType.1               893594 non-null  object
 26  MlsStatus                    893594 non-null  object
 27  ElementarySchool             83104 non-null   object
 28  AttachedGarageYN             589448 non-null  object
 29  ParkingTotal                 839102 non-null  float64
 30  PropertySubType              785189 non-null  object
 31  LotSizeAcres                 808569 non-null  float64
 32  SubdivisionName              298187 non-null  object
 33  BuyerOfficeAOR               235140 non-null  object
 34  YearBuilt                    821420 non-null  float64
 35  DaysOnMarket.1               893594 non-null  int64
 36  StreetNumberNumeric          889570 non-null  float64
 37  LivingArea.1                 782759 non-null  float64
 38  ListingId                    893594 non-null  object
 39  BathroomsTotalInteger        820694 non-null  float64
 40  City                         892617 non-null  object
 41  TaxYear                      901 non-null     float64
 42  BuildingAreaTotal            143313 non-null  float64
 43  BedroomsTotal                786298 non-null  float64
 44  ContractStatusChangeDate     886138 non-null  datetime64[ns]
 45  Longitude.1                  781848 non-null  float64
 46  CoBuyerAgentFirstName        19810 non-null   object
 47  PurchaseContractDate         377495 non-null  datetime64[ns]
 48  ListingContractDate          893594 non-null  datetime64[ns]
 49  BelowGradeFinishedArea       3621 non-null    float64
 50  Latitude.1                   781122 non-null  float64
 51  ListPrice.1                  891376 non-null  float64
 52  StateOrProvince              893525 non-null  object
 53  FireplaceYN                  765975 non-null  object
 54  Stories                      661815 non-null  float64
 55  HighSchool                   109303 non-null  object
 56  Levels                       721823 non-null  object
 57  CloseDate.1                  257985 non-null  object
 58  LotSizeDimensions            51050 non-null   object
 59  LotSizeArea                  812504 non-null  float64
 60  MainLevelBedrooms            412951 non-null  float64
 61  NewConstructionYN            774028 non-null  object
 62  GarageSpaces                 724634 non-null  float64
 63  HighSchoolDistrict           538808 non-null  object
 64  PostalCode                   893376 non-null  object
 65  BuyerOfficeName.1            247055 non-null  object
 66  AssociationFee               604893 non-null  float64
 67  LotSizeSquareFeet            811392 non-null  float64
 68  UnparsedAddress.1            891239 non-null  object
 69  BuyerAgencyCompensationType  123538 non-null  object
 70  BuyerAgencyCompensation      123519 non-null  float64
 71  year_month                   893594 non-null  object
dtypes: datetime64[ns](4), float64(27), int64(4), object(37)
memory usage: 490.9+ MB

# Numeric Type Checking

In [ ]:
int_list = int_list.copy()

In [ ]:
parking_vals = int_list['ParkingTotal'].unique()

display(parking_vals) # are half parking spaces valid? idk

In [ ]:
to_int_cols = [
    "YearBuilt",
    "StreetNumberNumeric",
    "BathroomsTotalInteger",
    "TaxYear",
    "Stories",
]

int_list[to_int_cols] = int_list[to_int_cols].astype("Int64")