# Making final dataset before tableau stuff begins

# Setup

In [1]:
# imports
import pandas as pd
from idx.components import ingest, preprocessing, feature_engineering, cleaning
from sklearn.pipeline import Pipeline
import geopandas as gpd

In [2]:
# making school district geodataframe
district_gdf = gpd.read_file("../data/raw/district/DistrictAreas2425.shp")
district_gdf = district_gdf.to_crs(epsg=4326)

# initializing pipeline components
ingestor = ingest.MLSIngestor(input_path="../data/raw/")
fred_ingestor = ingest.FredMerger()
cleaner = preprocessing.DataCleaner()
flagger = preprocessing.BadDataFlagger()
market_maker = feature_engineering.CreateMarketMetrics()
cleanup = feature_engineering.CleanUpTransformer()
null = feature_engineering.NullDropper()
dist_merger = feature_engineering.DistrictMerger(district_gdf=district_gdf)
iqr_flagger = cleaning.OutlierFlagger(subset=["OriginalListPrice", "LivingArea", "LotSizeArea"])

ingest_test = Pipeline([ 
    ("ingestor", ingestor),
    ("fred_ingestor", fred_ingestor),
    ("cleaner", cleaner),
    ("flagger", flagger),
    ("market_maker", market_maker),
    ("cleanup", cleanup),
    ("null", null),
    ("dist_merger", dist_merger),
    ("iqr_flagger", iqr_flagger)
])


df_sold, df_listings = ingest_test.fit_transform(X=None, y=None)

Read 31 files from ../data/raw with filter 'Sold'


Read 28 files from ../data/raw with filter 'Listing'


Merged FRED data with sold data: 681599 rows
Merged FRED data with listings data: 893594 rows


Original sold_df shape: (681599, 87)
Original listings_df shape: (893594, 87)
Post-drop sold_df shape: (681599, 72)
Post-drop listings_df shape: (893594, 61)
4 datetime columns converted and 5 integer columns converted.
Dropped 9 non-analysis columns from sold_df and listings_df.
Flagged 215 rows with impossible measurements.
Flagged 0 rows with impossible year.
Flagged 124 rows with listing after close.
Flagged 435 rows with purchase after close.
Flagged 430 rows with negative timeline.
Flagged 19411 rows with null coordinates.
Flagged 46 rows with placeholder coordinates.
Flagged 232 rows with non-California coordinates.
Flagged 223 rows with impossible measurements.
Flagged 41 rows with impossible year.
Flagged 140 rows with listing after close.
Flagged 351 rows with purchase after close.
Flagged 406 rows with negative timeline.
Flagged 112475 rows with null coordinates.
Flagged 101 rows with placeholder coordinates.
Flagged 611 rows with non-California coordinates.


Pre-feature engineering column count for sold_df and listings_df: 71 and 60
Post-feature engineering column count for sold_df and listings_df: 77 and 66
Dropped columns: ['TaxYear', 'BuildingAreaTotal', 'LotSizeDimensions', 'StreetNumberNumeric', 'MainLevelBedrooms']. New shapes: sold_df: (681599, 72), listings_df: (893594, 61)
Dropping nulls from columns: ['Latitude', 'Longitude', 'OriginalListPrice', 'ClosePrice']. Pre-null drop shapes: sold_df: (681599, 72), listings_df: (893594, 61)
Post-null drop shapes: sold_df: (660343, 72), listings_df: (778218, 61)
Merging geographic district information. Pre-merge shapes: sold_df: (660343, 72), listings_df: (778218, 61)
Post-merge shapes: sold_df: (803696, 74), listings_df: (938118, 63)


Flagging IQR outliers (range=1.5*IQR) in columns: ['OriginalListPrice', 'LivingArea', 'LotSizeArea']. Pre-flag shapes: sold_df: (803696, 74), listings_df: (938118, 63)
Flagged IQR outliers (range=1.5*IQR) in columns: ['OriginalListPrice', 'LivingArea', 'LotSizeArea']. Post-flag shapes: sold_df: (803696, 75), listings_df: (938118, 64)

In [3]:
display(df_listings.head())

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,ListPrice,...,non_cali_coords_flag,price_ratio,price_per_sqft,days_on_market,yr_month,listing_to_contract_days,contract_to_close_days,index_right,DistrictNa,outlier_flag
2,1400000.0,1076193814,NaT,NaN,33.858559,-116.542169,505 E Molino Road,Residential,2256.0,1400000.0,...,False,NaN,NaN,NaN,NaT,NaN,NaN,478.0,Palm Springs Unified,False
8,199990.0,1076192982,NaT,NaN,32.777540,-115.553772,1826 S 4th Street,Residential,1024.0,199990.0,...,False,NaN,NaN,NaN,NaT,NaN,NaN,149.0,Central Union High,False
8,199990.0,1076192982,NaT,NaN,32.777540,-115.553772,1826 S 4th Street,Residential,1024.0,199990.0,...,False,NaN,NaN,NaN,NaT,NaN,NaN,150.0,El Centro Elementary,False
11,835000.0,1076190486,NaT,NaN,33.166112,-117.266548,4645 Cordoba Way,Residential,1444.0,835000.0,...,False,NaN,NaN,NaN,NaT,NaN,NaN,582.0,Vista Unified,False
12,1150000.0,1076190201,NaT,NaN,33.212280,-117.218628,1517 Via Pedro,Residential,3309.0,1150000.0,...,False,NaN,NaN,NaN,NaT,NaN,NaN,582.0,Vista Unified,False

In [4]:
display(df_listings.info())

<class 'pandas.core.frame.DataFrame'>
Index: 938118 entries, 2 to 893593
Data columns (total 64 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   OriginalListPrice            938118 non-null  float64
 1   ListingKey                   938118 non-null  int64
 2   CloseDate                    276734 non-null  datetime64[ns]
 3   ClosePrice                   253027 non-null  float64
 4   Latitude                     938118 non-null  float64
 5   Longitude                    938118 non-null  float64
 6   UnparsedAddress              935777 non-null  object
 7   PropertyType                 938118 non-null  object
 8   LivingArea                   823521 non-null  float64
 9   ListPrice                    938096 non-null  float64
 10  DaysOnMarket                 938118 non-null  int64
 11  ListOfficeName               938118 non-null  object
 12  BuyerOfficeName              263405 non-null  object
 13  CoListOfficeName             187006 non-null  object
 14  AssociationFeeFrequency      271987 non-null  object
 15  ListingKeyNumeric            938118 non-null  int64
 16  MLSAreaMajor                 843935 non-null  object
 17  CountyOrParish               938118 non-null  object
 18  MlsStatus                    938118 non-null  object
 19  AttachedGarageYN             624848 non-null  object
 20  ParkingTotal                 878860 non-null  float64
 21  PropertySubType              821846 non-null  object
 22  LotSizeAcres                 853566 non-null  float64
 23  YearBuilt                    861351 non-null  Int64
 24  ListingId                    938118 non-null  object
 25  BathroomsTotalInteger        860130 non-null  Int64
 26  City                         937258 non-null  object
 27  BedroomsTotal                827068 non-null  float64
 28  CoBuyerAgentFirstName        21165 non-null   object
 29  PurchaseContractDate         402143 non-null  datetime64[ns]
 30  ListingContractDate          938118 non-null  datetime64[ns]
 31  StateOrProvince              938063 non-null  object
 32  FireplaceYN                  804662 non-null  object
 33  Stories                      700943 non-null  Int64
 34  Levels                       761176 non-null  object
 35  LotSizeArea                  857873 non-null  float64
 36  NewConstructionYN            805576 non-null  object
 37  GarageSpaces                 763920 non-null  float64
 38  HighSchoolDistrict           581120 non-null  object
 39  PostalCode                   937899 non-null  object
 40  AssociationFee               650500 non-null  float64
 41  LotSizeSquareFeet            856402 non-null  float64
 42  source_file                  938118 non-null  object
 43  BuyerAgencyCompensationType  114301 non-null  object
 44  BuyerAgencyCompensation      114499 non-null  float64
 45  year_month                   938118 non-null  period[M]
 46  rate_30yr_fixed              938118 non-null  float64
 47  impossible_measurement_flag  938118 non-null  boolean
 48  impossible_year_flag         861351 non-null  boolean
 49  listing_after_close_flag     938118 non-null  bool
 50  purchase_after_close_flag    938118 non-null  bool
 51  negative_timeline_flag       938118 non-null  bool
 52  null_coords_flag             938118 non-null  bool
 53  placeholder_coords_flag      938118 non-null  bool
 54  non_cali_coords_flag         938118 non-null  bool
 55  price_ratio                  253027 non-null  float64
 56  price_per_sqft               240572 non-null  float64
 57  days_on_market               276734 non-null  float64
 58  yr_month                     276734 non-null  period[M]
 59  listing_to_contract_days     402143 non-null  float64
 60  contract_to_close_days       270414 non-null  float64
 61  index_right                  937279 non-null  float64
 62  DistrictNa                   937279 non-null  object
 63  outlier_flag                 938118 non-null  bool
dtypes: Int64(3), bool(7), boolean(2), datetime64[ns](3), float64(21), int64(3), object(23), period[M](2)
memory usage: 413.3+ MB

None

# something

In [5]:
# TODO : save a df with bad data removed and one with all the flags still
# Include a written comparison of dataset size and median values before and after filtering. OK

In [6]:
def drop_flagged(df, flag_columns):
    """
    Drops rows from the DataFrame where any of the specified flag columns are True.
    
    Parameters:
    df (pd.DataFrame): The input DataFrame.
    flag_columns (list): List of column names that contain boolean flags.
    
    Returns:
    pd.DataFrame: A new DataFrame with flagged rows removed.
    """
    # Create a boolean mask where any of the flag columns are True
    mask = df[flag_columns].any(axis=1)
    
    # Return a new DataFrame with flagged rows removed
    return df[~mask]

In [7]:
flag_columns = [col for col in df_listings.columns if 'flag' in col.lower()]

df_sold_cleared = drop_flagged(df_sold, flag_columns)
df_listings_cleared = drop_flagged(df_listings, flag_columns)

In [8]:
display(df_sold_cleared.info())
display(df_sold_cleared.shape)

<class 'pandas.core.frame.DataFrame'>
Index: 689609 entries, 0 to 681594
Data columns (total 75 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Flooring                     402912 non-null  object
 1   ViewYN                       623498 non-null  object
 2   WaterfrontYN                 393 non-null     object
 3   BasementYN                   10304 non-null   object
 4   PoolPrivateYN                607149 non-null  object
 5   OriginalListPrice            689609 non-null  float64
 6   ListingKey                   689609 non-null  int64
 7   CloseDate                    689609 non-null  datetime64[ns]
 8   ClosePrice                   689609 non-null  float64
 9   Latitude                     689609 non-null  float64
 10  Longitude                    689609 non-null  float64
 11  UnparsedAddress              688742 non-null  object
 12  PropertyType                 689609 non-null  object
 13  LivingArea                   650237 non-null  float64
 14  ListPrice                    689604 non-null  float64
 15  DaysOnMarket                 689609 non-null  int64
 16  ListOfficeName               689609 non-null  object
 17  BuyerOfficeName              680207 non-null  object
 18  CoListOfficeName             145348 non-null  object
 19  AssociationFeeFrequency      197610 non-null  object
 20  ListingKeyNumeric            689609 non-null  int64
 21  MLSAreaMajor                 615805 non-null  object
 22  CountyOrParish               689609 non-null  object
 23  MlsStatus                    689609 non-null  object
 24  AttachedGarageYN             521759 non-null  object
 25  ParkingTotal                 675636 non-null  float64
 26  PropertySubType              641832 non-null  object
 27  LotSizeAcres                 612479 non-null  float64
 28  YearBuilt                    669513 non-null  Int64
 29  BuyerAgencyCompensationType  122750 non-null  object
 30  ListingId                    689609 non-null  object
 31  BathroomsTotalInteger        664954 non-null  Int64
 32  City                         689225 non-null  object
 33  BuyerAgencyCompensation      122928 non-null  float64
 34  BedroomsTotal                652523 non-null  float64
 35  CoBuyerAgentFirstName        54511 non-null   object
 36  PurchaseContractDate         678516 non-null  datetime64[ns]
 37  ListingContractDate          689539 non-null  datetime64[ns]
 38  StateOrProvince              689609 non-null  object
 39  FireplaceYN                  636553 non-null  object
 40  Stories                      557449 non-null  Int64
 41  Levels                       595279 non-null  object
 42  LotSizeArea                  614735 non-null  float64
 43  NewConstructionYN            600773 non-null  object
 44  GarageSpaces                 622144 non-null  float64
 45  HighSchoolDistrict           482305 non-null  object
 46  PostalCode                   689463 non-null  object
 47  AssociationFee               487841 non-null  float64
 48  LotSizeSquareFeet            614256 non-null  float64
 49  latfilled                    171127 non-null  object
 50  lonfilled                    171127 non-null  object
 51  source_file                  689609 non-null  object
 52  BuyerAgentAOR                560695 non-null  object
 53  ListAgentAOR                 566393 non-null  object
 54  OriginatingSystemName        82374 non-null   object
 55  OriginatingSystemSubName     82374 non-null   object
 56  year_month                   689609 non-null  period[M]
 57  rate_30yr_fixed              689609 non-null  float64
 58  impossible_measurement_flag  689609 non-null  boolean
 59  impossible_year_flag         669513 non-null  boolean
 60  listing_after_close_flag     689609 non-null  bool
 61  purchase_after_close_flag    689609 non-null  bool
 62  negative_timeline_flag       689609 non-null  bool
 63  null_coords_flag             689609 non-null  bool
 64  placeholder_coords_flag      689609 non-null  bool
 65  non_cali_coords_flag         689609 non-null  bool
 66  price_ratio                  689609 non-null  float64
 67  price_per_sqft               650235 non-null  float64
 68  days_on_market               689539 non-null  float64
 69  yr_month                     689609 non-null  period[M]
 70  listing_to_contract_days     678449 non-null  float64
 71  contract_to_close_days       678516 non-null  float64
 72  index_right                  689492 non-null  float64
 73  DistrictNa                   689492 non-null  object
 74  outlier_flag                 689609 non-null  bool
dtypes: Int64(3), bool(7), boolean(2), datetime64[ns](3), float64(21), int64(3), object(34), period[M](2)
memory usage: 361.7+ MB

None

(689609, 75)

In [9]:
display(df_listings_cleared.info())
display(df_listings_cleared.shape)

<class 'pandas.core.frame.DataFrame'>
Index: 797240 entries, 2 to 893593
Data columns (total 64 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   OriginalListPrice            797240 non-null  float64
 1   ListingKey                   797240 non-null  int64
 2   CloseDate                    246339 non-null  datetime64[ns]
 3   ClosePrice                   224012 non-null  float64
 4   Latitude                     797240 non-null  float64
 5   Longitude                    797240 non-null  float64
 6   UnparsedAddress              795273 non-null  object
 7   PropertyType                 797240 non-null  object
 8   LivingArea                   718951 non-null  float64
 9   ListPrice                    797221 non-null  float64
 10  DaysOnMarket                 797240 non-null  int64
 11  ListOfficeName               797240 non-null  object
 12  BuyerOfficeName              233771 non-null  object
 13  CoListOfficeName             159686 non-null  object
 14  AssociationFeeFrequency      225039 non-null  object
 15  ListingKeyNumeric            797240 non-null  int64
 16  MLSAreaMajor                 715054 non-null  object
 17  CountyOrParish               797240 non-null  object
 18  MlsStatus                    797240 non-null  object
 19  AttachedGarageYN             554395 non-null  object
 20  ParkingTotal                 764308 non-null  float64
 21  PropertySubType              714950 non-null  object
 22  LotSizeAcres                 713058 non-null  float64
 23  YearBuilt                    752533 non-null  Int64
 24  ListingId                    797240 non-null  object
 25  BathroomsTotalInteger        746772 non-null  Int64
 26  City                         796809 non-null  object
 27  BedroomsTotal                722069 non-null  float64
 28  CoBuyerAgentFirstName        18722 non-null   object
 29  PurchaseContractDate         356803 non-null  datetime64[ns]
 30  ListingContractDate          797240 non-null  datetime64[ns]
 31  StateOrProvince              797236 non-null  object
 32  FireplaceYN                  701593 non-null  object
 33  Stories                      613090 non-null  Int64
 34  Levels                       662062 non-null  object
 35  LotSizeArea                  717177 non-null  float64
 36  NewConstructionYN            681349 non-null  object
 37  GarageSpaces                 674366 non-null  float64
 38  HighSchoolDistrict           509147 non-null  object
 39  PostalCode                   797060 non-null  object
 40  AssociationFee               552158 non-null  float64
 41  LotSizeSquareFeet            716077 non-null  float64
 42  source_file                  797240 non-null  object
 43  BuyerAgencyCompensationType  96508 non-null   object
 44  BuyerAgencyCompensation      96698 non-null   float64
 45  year_month                   797240 non-null  period[M]
 46  rate_30yr_fixed              797240 non-null  float64
 47  impossible_measurement_flag  797240 non-null  boolean
 48  impossible_year_flag         752533 non-null  boolean
 49  listing_after_close_flag     797240 non-null  bool
 50  purchase_after_close_flag    797240 non-null  bool
 51  negative_timeline_flag       797240 non-null  bool
 52  null_coords_flag             797240 non-null  bool
 53  placeholder_coords_flag      797240 non-null  bool
 54  non_cali_coords_flag         797240 non-null  bool
 55  price_ratio                  224012 non-null  float64
 56  price_per_sqft               214262 non-null  float64
 57  days_on_market               246339 non-null  float64
 58  yr_month                     246339 non-null  period[M]
 59  listing_to_contract_days     356803 non-null  float64
 60  contract_to_close_days       240977 non-null  float64
 61  index_right                  796996 non-null  float64
 62  DistrictNa                   796996 non-null  object
 63  outlier_flag                 797240 non-null  bool
dtypes: Int64(3), bool(7), boolean(2), datetime64[ns](3), float64(21), int64(3), object(23), period[M](2)
memory usage: 351.3+ MB

None

(797240, 64)

In [10]:
print("Original df_sold shape:", df_sold.shape)
print("Cleared df_sold shape:", df_sold_cleared.shape)
print("Original df_listings shape:", df_listings.shape)
print("Cleared df_listings shape:", df_listings_cleared.shape)

Original df_sold shape: (803696, 75)
Cleared df_sold shape: (689609, 75)
Original df_listings shape: (938118, 64)
Cleared df_listings shape: (797240, 64)

In [11]:
df_listings_cleared.head()

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,ListPrice,...,non_cali_coords_flag,price_ratio,price_per_sqft,days_on_market,yr_month,listing_to_contract_days,contract_to_close_days,index_right,DistrictNa,outlier_flag
2,1400000.0,1076193814,NaT,NaN,33.858559,-116.542169,505 E Molino Road,Residential,2256.0,1400000.0,...,False,NaN,NaN,NaN,NaT,NaN,NaN,478.0,Palm Springs Unified,False
8,199990.0,1076192982,NaT,NaN,32.777540,-115.553772,1826 S 4th Street,Residential,1024.0,199990.0,...,False,NaN,NaN,NaN,NaT,NaN,NaN,149.0,Central Union High,False
8,199990.0,1076192982,NaT,NaN,32.777540,-115.553772,1826 S 4th Street,Residential,1024.0,199990.0,...,False,NaN,NaN,NaN,NaT,NaN,NaN,150.0,El Centro Elementary,False
11,835000.0,1076190486,NaT,NaN,33.166112,-117.266548,4645 Cordoba Way,Residential,1444.0,835000.0,...,False,NaN,NaN,NaN,NaT,NaN,NaN,582.0,Vista Unified,False
12,1150000.0,1076190201,NaT,NaN,33.212280,-117.218628,1517 Via Pedro,Residential,3309.0,1150000.0,...,False,NaN,NaN,NaN,NaT,NaN,NaN,582.0,Vista Unified,False

In [12]:
"""df_sold_cleared.to_csv("../data/processed/df_sold_cleared.csv", index=False)
df_listings_cleared.to_csv("../data/processed/df_listings_cleared.csv", index=False)
df_sold.to_csv("../data/processed/df_sold.csv", index=False)
df_listings.to_csv("../data/processed/df_listings.csv", index=False)"""

'df_sold_cleared.to_csv("../data/processed/df_sold_cleared.csv", index=False)\ndf_listings_cleared.to_csv("../data/processed/df_listings_cleared.csv", index=False)\ndf_sold.to_csv("../data/processed/df_sold.csv", index=False)\ndf_listings.to_csv("../data/processed/df_listings.csv", index=False)'